allowBuilds:
  '@parcel/watcher': set this to true or false
  bufferutil: set this to true or false
  es5-ext: set this to true or false
  utf-8-validate: set this to true or false
minimumReleaseAgeExclude:
  - '@salla.sa/applepay@2.14.466'
  - '@salla.sa/base@2.14.466'
  - '@salla.sa/twilight-components@2.14.466'
  - '@salla.sa/twilight-tailwind-theme@2.14.466'
  - '@salla.sa/twilight@2.14.466'
